// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNoteTitle() {
  return window['go']['main']['App']['GetNoteTitle']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LoadNote() {
  return window['go']['main']['App']['LoadNote']();
}

export function NewNote() {
  return window['go']['main']['App']['NewNote']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function TogglePin() {
  return window['go']['main']['App']['TogglePin']();
}
